# Generated by Django 3.2 on 2022-10-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20221021_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='post_date',
            field=models.DateField(),
        ),
    ]
